### ISSUE TITLE
Wallet Chain Automatically Switches from Geneva to zkEVM in MNS Dapp

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/mns-app#26]
When attempting to connect the wallet in the MNS dapp, there's an issue where the chain automatically switches from Geneva to zkEVM. This behavior is not consistent as other dapps works fine and this may impact user experience

![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/236ecc80-7e82-46f2-bb00-b3496bd552b0)

**Comment by hairyf** [comment]
fixed

**Comment by SanghamitraBhowmick1993** [comment]
This is working 

![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/4cbec785-cac0-47e7-b2cf-d46e9ec16968)

**Comment by SanghamitraBhowmick1993** [comment]
This is occuring again. Is there something that needs to be checked again? @hairyf 


![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/3fc1bb9f-1f4f-4a63-9dda-2d5703304144)

**Comment by hairyf** [comment]
updated

**Comment by SanghamitraBhowmick1993** [comment]
Still does not work for me


![Image](https://github.com/MXCzkEVM/mns-app/assets/93600163/1a765753-d7eb-439b-8a85-dbfd81a1fc71)

**Comment by FTI1DS** [comment]
I also have the same Issue 

![Image](https://github.com/MXCzkEVM/mns-app/assets/129849693/16c53662-168b-4b4c-bc1d-6aef3dca8a43)

**Comment by SanghamitraBhowmick1993** [comment]
Additionally, the account does not switch even if MetaMask is set to a different account (e.g., Account 1). MNS still displays a different or older account instead of showing Account 1.



![Image](https://github.com/user-attachments/assets/dc1dba98-b752-423a-bfba-37bcaec0ef87)

cc: @sheenhx

**Comment by hairyf** [comment]
![image](https://github.com/user-attachments/assets/761e3b15-dcf7-4207-8f10-b5aee69b752b)

**Comment by hairyf** [comment]
> Additionally, the account does not switch even if MetaMask is set to a different account (e.g., Account 1). MNS still displays a different or older account instead of showing Account 1.

@SanghamitraBhowmick1993 

Switching accounts in metamask is not related to the account connected to the webpage

**Comment by SanghamitraBhowmick1993** [comment]
works for geneva now, but the change is not working for mainnet @hairyf 
![Image](https://github.com/user-attachments/assets/2651c06e-34d1-44f4-9efd-8b18629716bb)

**Comment by SanghamitraBhowmick1993** [comment]
working as expected
